on: [pull_request]

name: Validate
jobs:
  kubeval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: test
        uses: Anugrahchaturvedi/helm-kubeval-action@devtron
        with:
          path: 'chart'
