on: [pull_request]

name: Validate
jobs:
  kubeval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: test
        uses: Anugrahchaturvedi/actions-repo@master
        with:
          path: 'chart'
